### What is TensorFlow?

### Tasks: use tensorflow only
1) Create a tensor,define a simple model and print its summary.
2) Generate a random tensor(3*3),print it
3) Perfor matrix multiplication and print the result
4) Create two tensor and perform elementwise addition.

In [ ]:
import tensorflow as tf

# Create a tensor
x = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print("Tensor x:\n", x)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(1)
])

# Print model summary
model.summary()


Tensor x:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 33 (132.00 B)

 Trainable params: 33 (132.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
random_tensor = tf.random.uniform(shape=(3, 3), minval=0, maxval=1)
print("Random 3x3 Tensor:\n", random_tensor)


Random 3x3 Tensor:
 tf.Tensor(
[[0.7075906  0.22582948 0.795684  ]
 [0.9887607  0.3360802  0.7532073 ]
 [0.12281013 0.23670197 0.2110883 ]], shape=(3, 3), dtype=float32)


In [ ]:
A = tf.constant([[1, 2],
                 [3, 4]])

B = tf.constant([[5, 6],
                 [7, 8]])

matmul_result = tf.matmul(A, B)
print("Matrix Multiplication Result:\n", matmul_result)


Matrix Multiplication Result:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([4, 5, 6])

add_result = tf.add(t1, t2)
print("Element-wise Addition:\n", add_result)


Element-wise Addition:
 tf.Tensor([5 7 9], shape=(3,), dtype=int32)


***Use Keras***  

Ques 2: Define a 2-layer sequential model,compile it, and run for 30 epochs and print the predicted result:  
X=[1,2,3,4]  
Y=[2,4,6,8]  
or Y=2X
Predict sum of two numbers.

***Use Pytorch***  
1) Create a tensor(2*2),print it, then generate a random tensor(3*3) perform elementwise addition and print the result.
2) Define a simple neural n/w and print its structure.

In [1]:
# Import libraries
import torch
import torch.nn as nn
import torch.optim as optim

# Training Data
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
Y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])

# Define 2-layer Sequential Model
model = nn.Sequential(
    nn.Linear(1, 4),   # Input layer → Hidden layer
    nn.ReLU(),
    nn.Linear(4, 1)    # Hidden layer → Output layer
)

# Print model structure
print("Model Structure:")
print(model)

# Loss Function and Optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training for 30 epochs
epochs = 30

for epoch in range(epochs):

    # Forward pass
    outputs = model(X)

    # Calculate loss
    loss = criterion(outputs, Y)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print loss
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

# Prediction
test = torch.tensor([[5.0]])

predicted = model(test)

print("\nPredicted Result for X = 5:")
print(predicted.item())

Model Structure:
Sequential(
  (0): Linear(in_features=1, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)
Epoch [1/30], Loss: 35.0648
Epoch [2/30], Loss: 33.6762
Epoch [3/30], Loss: 32.1632
Epoch [4/30], Loss: 30.5679
Epoch [5/30], Loss: 28.7162
Epoch [6/30], Loss: 26.3831
Epoch [7/30], Loss: 23.4454
Epoch [8/30], Loss: 19.7146
Epoch [9/30], Loss: 15.0206
Epoch [10/30], Loss: 9.9036
Epoch [11/30], Loss: 5.3076
Epoch [12/30], Loss: 2.1815
Epoch [13/30], Loss: 0.6750
Epoch [14/30], Loss: 0.1684
Epoch [15/30], Loss: 0.0426
Epoch [16/30], Loss: 0.0170
Epoch [17/30], Loss: 0.0121
Epoch [18/30], Loss: 0.0111
Epoch [19/30], Loss: 0.0107
Epoch [20/30], Loss: 0.0105
Epoch [21/30], Loss: 0.0103
Epoch [22/30], Loss: 0.0100
Epoch [23/30], Loss: 0.0098
Epoch [24/30], Loss: 0.0096
Epoch [25/30], Loss: 0.0094
Epoch [26/30], Loss: 0.0092
Epoch [27/30], Loss: 0.0090
Epoch [28/30], Loss: 0.0088
Epoch [29/30], Loss: 0.0087
Epoch [30/30], Loss: 0.0085

Pr